#!/usr/bin/env bash
# Local stack: Postgres + FusionAuth + a local.* hostname edge in Docker.
# Mirrors the box topology — same images, same first-boot role separation
# (containers/simulationDB/initdb) — but with throwaway dev credentials and
# everything on localhost. simulationAPI and simulationWeb still run natively
# (npm run dev); this covers the stateful/upstream pieces plus a tiny nginx
# that stands in for reverseProxy, routing the prod-like local hostnames:
#
#   http://local.allin.makejohnacoffee.com  -> API gateway (login wall + SPA)
#   http://local.api.makejohnacoffee.com    -> API backend (results CRUD)
#   http://local.id.makejohnacoffee.com     -> FusionAuth
#
# Usage:
#   ./cmd local-stack hosts     # one-time: point the local.* names at 127.0.0.1 in /etc/hosts (sudo)
#   ./cmd local-stack [up]      # start; waits until healthy
#   ./cmd local-stack down      # stop, keep data
#   ./cmd local-stack reset     # stop and delete the data volume (re-runs initdb + kickstart)
#   ./cmd local-stack status    # container/health overview
#
# FusionAuth is provisioned on first boot by scripts/local-stack/kickstart.json:
# tenant issuer, the poker_equity app (prod client id, generated secret), and
# users admin@example.com / player@example.com (generated passwords).
# The OAuth client secret, user passwords, JWT signing key id and kickstart
# API key are NOT committed: this script generates
# containers/simulationAPI/.env.local (gitignored) with random values and
# exports them so kickstart provisions FusionAuth with the same.
# Postgres creds match simulationAPI's DATABASE_URL default, so the API needs
# no env for plain-localhost work: postgresql://simulation:simulation@localhost:5432/simulation
# For the local.* hostnames, run the API with `npm run dev:local` (loads .env.local).
# Port clashes: override with LOCAL_PG_PORT / LOCAL_FA_PORT / LOCAL_EDGE_PORT.
set -euo pipefail

usage() { echo "usage: $0 [up|down|reset|status|hosts]" >&2; exit 2; }

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT=big-equity-local
PG_PORT="${LOCAL_PG_PORT:-5432}"
FA_PORT="${LOCAL_FA_PORT:-9011}"
EDGE_PORT="${LOCAL_EDGE_PORT:-80}"
LOCAL_HOSTS="local.allin.makejohnacoffee.com local.api.makejohnacoffee.com local.id.makejohnacoffee.com"
ENV_FILE="${REPO}/containers/simulationAPI/.env.local"

# .env.local is generated, never committed: the OAuth client secret and the
# kickstart user passwords are random per checkout. The same values are
# exported for the fusionauth service so kickstart.json (#{ENV.…}) provisions
# the app and users with them. Kickstart only runs against an empty database,
# so to rotate: delete .env.local, then ./cmd local-stack reset && ./cmd local-stack up.
ensure_env() {
  if [[ ! -f "$ENV_FILE" ]]; then
    cat > "$ENV_FILE" <<ENV
# Generated by scripts/local-stack.sh — gitignored. Loaded by 'npm run dev:local'
# for the prod-like local.* aliases; plain 'npm run dev' (localhost only) needs
# none of this. To rotate the secret: delete this file, then
# ./cmd local-stack reset && ./cmd local-stack up (kickstart re-provisions FusionAuth).
AUTH_ISSUER=http://local.id.makejohnacoffee.com
AUTH_APP_URL=http://local.allin.makejohnacoffee.com
AUTH_REDIRECT_URI=http://local.allin.makejohnacoffee.com/auth/callback
AUTH_CLIENT_SECRET=$(openssl rand -hex 32)
# Derived would be allin.makejohnacoffee.com (strips one label), which the
# local.api.… hostname doesn't match — pin the shared parent explicitly.
AUTH_COOKIE_DOMAIN=makejohnacoffee.com
WEB_ORIGIN=http://local.allin.makejohnacoffee.com
# The login wall proxies to the Vite dev server instead of the nginx SPA container.
WEB_UPSTREAM=http://localhost:5173
# FusionAuth users provisioned by kickstart on first boot (not read by the
# API). Rotate like the secret: delete this file, then reset && up.
LOCAL_ADMIN_PASSWORD=$(openssl rand -hex 4)
LOCAL_PLAYER_PASSWORD=$(openssl rand -hex 4)
# Kickstart-only too: the JWT signing key id and the FusionAuth API key it
# creates on first boot.
LOCAL_SIGNING_KEY_ID=$(uuidgen | tr '[:upper:]' '[:lower:]')
LOCAL_KICKSTART_API_KEY=$(openssl rand -hex 32)
ENV
    echo "generated containers/simulationAPI/.env.local (fresh AUTH_CLIENT_SECRET + user passwords)"
  fi
  # Files generated before these kickstart values existed: top them up.
  # New values only reach FusionAuth on a kickstart re-run (reset && up).
  local var val
  for var in LOCAL_ADMIN_PASSWORD LOCAL_PLAYER_PASSWORD LOCAL_SIGNING_KEY_ID LOCAL_KICKSTART_API_KEY; do
    if ! grep -q "^${var}=" "$ENV_FILE"; then
      case "$var" in
        LOCAL_SIGNING_KEY_ID)    val="$(uuidgen | tr '[:upper:]' '[:lower:]')" ;;
        LOCAL_KICKSTART_API_KEY) val="$(openssl rand -hex 32)" ;;
        *)                       val="$(openssl rand -hex 4)" ;;
      esac
      echo "${var}=${val}" >> "$ENV_FILE"
      echo "added ${var} to containers/simulationAPI/.env.local (applies after ./cmd local-stack reset && up)"
    fi
  done
  AUTH_CLIENT_SECRET="$(sed -n 's/^AUTH_CLIENT_SECRET=//p' "$ENV_FILE")"
  LOCAL_ADMIN_PASSWORD="$(sed -n 's/^LOCAL_ADMIN_PASSWORD=//p' "$ENV_FILE")"
  LOCAL_PLAYER_PASSWORD="$(sed -n 's/^LOCAL_PLAYER_PASSWORD=//p' "$ENV_FILE")"
  LOCAL_SIGNING_KEY_ID="$(sed -n 's/^LOCAL_SIGNING_KEY_ID=//p' "$ENV_FILE")"
  LOCAL_KICKSTART_API_KEY="$(sed -n 's/^LOCAL_KICKSTART_API_KEY=//p' "$ENV_FILE")"
  export AUTH_CLIENT_SECRET LOCAL_ADMIN_PASSWORD LOCAL_PLAYER_PASSWORD \
    LOCAL_SIGNING_KEY_ID LOCAL_KICKSTART_API_KEY
}
ensure_env

# Everything below mirrors the per-container compose files under containers/,
# minus the prod-only parts (external simulation-net, mem_limits for the
# t3.micro, pipeline-written .env). Dev passwords equal the role names.
compose() {
  docker compose -p "$PROJECT" -f - "$@" <<EOF
services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: dbadmin
      POSTGRES_DB: simulation
      SIMULATION_ROLE_PASSWORD: simulation
      FUSIONAUTH_ROLE_PASSWORD: fusionauth
    ports:
      - "127.0.0.1:${PG_PORT}:5432"
    volumes:
      # PG 18: mount /var/lib/postgresql, not .../data (see simulationDB compose).
      - local-db-data:/var/lib/postgresql
      - ${REPO}/containers/simulationDB/initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbadmin -d simulation"]
      interval: 5s
      timeout: 5s
      retries: 12

  fusionauth:
    image: fusionauth/fusionauth-app:1.68.0
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USERNAME: dbadmin
      DATABASE_ROOT_PASSWORD: dbadmin
      DATABASE_USERNAME: fusionauth
      DATABASE_PASSWORD: fusionauth
      SEARCH_TYPE: database
      FUSIONAUTH_APP_MEMORY: 512M
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://local.id.makejohnacoffee.com
      FUSIONAUTH_APP_KICKSTART_FILE: /usr/local/fusionauth/kickstart/kickstart.json
      # First boot only: kickstart.json reads these via #{ENV.…}.
      AUTH_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}
      LOCAL_ADMIN_PASSWORD: ${LOCAL_ADMIN_PASSWORD}
      LOCAL_PLAYER_PASSWORD: ${LOCAL_PLAYER_PASSWORD}
      LOCAL_SIGNING_KEY_ID: ${LOCAL_SIGNING_KEY_ID}
      LOCAL_KICKSTART_API_KEY: ${LOCAL_KICKSTART_API_KEY}
    volumes:
      - ${REPO}/scripts/local-stack/kickstart.json:/usr/local/fusionauth/kickstart/kickstart.json:ro
    ports:
      - "127.0.0.1:${FA_PORT}:9011"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:9011/api/status"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s

  # Local stand-in for containers/reverseProxy: hostname routing only, no TLS.
  edge:
    image: nginx:alpine
    depends_on:
      - fusionauth
    volumes:
      - ${REPO}/scripts/local-stack/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "127.0.0.1:${EDGE_PORT}:80"
    # Lets the container reach the natively-running API on the host (Linux;
    # Docker Desktop provides host.docker.internal out of the box).
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # The local.* names must resolve INSIDE the compose network too — FusionAuth
    # calls itself at FUSIONAUTH_APP_URL (e.g. the admin UI's OAuth code
    # exchange), which /etc/hosts on the host can't cover.
    networks:
      default:
        aliases:
          - local.allin.makejohnacoffee.com
          - local.api.makejohnacoffee.com
          - local.id.makejohnacoffee.com

volumes:
  local-db-data:
EOF
}

case "${1:-up}" in
  up)
    compose up -d --wait
    # First boot only: kickstart PATCHes the tenant issuer, but FusionAuth
    # already cached the pre-kickstart tenant config — one restart flushes it
    # (the OIDC discovery doc keeps advertising the default issuer otherwise).
    if ! curl -fsS "http://localhost:${FA_PORT}/.well-known/openid-configuration" \
        | tr -d ' \n' | grep -q '"issuer":"http://local.id.makejohnacoffee.com"'; then
      echo "first boot: restarting fusionauth to flush its config cache"
      compose restart edge fusionauth >/dev/null 2>&1 || compose restart fusionauth
      compose up -d --wait
    fi
    echo
    echo "App (login wall): http://local.allin.makejohnacoffee.com"
    echo "API:              http://local.api.makejohnacoffee.com"
    echo "FusionAuth:       http://local.id.makejohnacoffee.com  (admin@example.com / LOCAL_ADMIN_PASSWORD in containers/simulationAPI/.env.local)"
    echo "Postgres:         postgresql://simulation:simulation@localhost:${PG_PORT}/simulation"
    echo
    echo "Now run the API with 'npm run dev:local' (containers/simulationAPI)"
    echo "and the SPA with 'npm run dev' (containers/simulationWeb)."
    echo "local.* names not resolving? Run: ./cmd local-stack hosts"
    ;;
  down)   compose down ;;
  reset)  compose down -v ;;
  status) compose ps ;;
  hosts)
    if grep -q "local.allin.makejohnacoffee.com" /etc/hosts; then
      echo "already in /etc/hosts:"
      grep "local.allin.makejohnacoffee.com" /etc/hosts
    else
      echo "Adding to /etc/hosts (needs sudo):"
      echo "127.0.0.1 ${LOCAL_HOSTS}"
      echo "127.0.0.1 ${LOCAL_HOSTS} # big-equity local-stack" | sudo tee -a /etc/hosts >/dev/null
      echo "done"
    fi
    ;;
  *) usage ;;
esac
